---
title: "Gov 50 Final Project"
author: "Melih Cevik"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---

## Project thoughts

Can the percentage of a town's fox news subscribers predict their GOP vote share. In this study, I plan to examine whether or not there is a correlation between the percentage of fox news subscribers, and whether the percentage of how many voted Republican in the 2000 presidential election. I hypothesize that towns with a greater percentage of fox news subscribers will see a greater percentage of those voting Republican. My explanatory variable is the share of subscribers to fox news in a town in the year 2000 , my response variable is Republican vote share in that town in the year 2000. If I observe, on average, a greater republican vote percentages in a town where there is a high prevalence of fox news, then my hypothesis will be correct. If I observe on average, a lower republican vote percentage in a town where there is a high share of fox news subscribers.

